<script setup>
import {
  computed,
  onMounted,
  ref,
} from 'vue'

// =========================
// Props
// =========================
//
// suburb:
// Activity suburb used to find matching
// weather data.
//
// activityTime:
// Activity date/time.
//
// Example:
// 2026-09-20 14:30:00
//
// activityTime is optional because some
// activities may not provide a usable time.
//
const props = defineProps({
  suburb: {
    type: String,
    required: true,
  },

  activityTime: {
    type: String,
    default: '',
  },
})

// =========================
// Component state
// =========================

// Matching suburb weather record.
const locationWeather = ref(null)

// Loading status.
const loading = ref(true)

// Error message.
const errorMessage = ref('')

// =========================
// Load weather JSON
// =========================
//
// Weather data is generated by:
//
// data_pipeline/fetch_open_meteo.py
//
// and stored at:
//
// public/data/melbourne_suburb_weather.json
//
onMounted(async () => {
  try {
    const response = await fetch(
      '/data/melbourne_suburb_weather.json',
    )

    if (!response.ok) {
      throw new Error(
        'Could not load weather data.',
      )
    }

    const data =
      await response.json()

    const suburb =
      String(
        props.suburb ?? '',
      ).trim()

    // Find matching suburb.
    //
    // Case-insensitive comparison avoids
    // small casing differences.
    locationWeather.value =
      data.locations?.find(
        (location) =>
          String(
            location.suburb ?? '',
          )
            .trim()
            .toLowerCase() ===
            suburb.toLowerCase() &&
          location.weather_available,
      ) || null
  } catch (error) {
    console.error(
      'Weather loading error:',
      error,
    )

    errorMessage.value =
      'Weather unavailable.'
  } finally {
    loading.value = false
  }
})

// =========================
// Activity hour
// =========================
//
// Example:
//
// 2026-09-20 14:30:00
//
// becomes:
//
// 2026-09-20T14:00
//
const activityHour = computed(() => {
  if (!props.activityTime) {
    return null
  }

  const match =
    String(
      props.activityTime,
    ).match(
      /(\d{4}-\d{2}-\d{2})[ T](\d{2})/,
    )

  if (!match) {
    return null
  }

  return `${match[1]}T${match[2]}:00`
})

// =========================
// Current Melbourne hour
// =========================
//
// Used as fallback when:
//
// - activity time is missing
// - activity date is outside
//   Open-Meteo's forecast range
//
const currentMelbourneHour =
  computed(() => {
    const melbourneTime =
      new Date().toLocaleString(
        'sv-SE',
        {
          timeZone:
            'Australia/Melbourne',
          hour12: false,
        },
      )

    return `${melbourneTime
      .slice(0, 13)
      .replace(' ', 'T')}:00`
  })

// =========================
// Find matching index
// =========================
//
// Priority:
//
// 1. Activity date/time
// 2. Current Melbourne hour
//
// This means:
//
// Activity inside forecast range
// -> activity forecast
//
// Activity outside forecast range
// -> current local conditions
//
function findBestHourIndex(
  hourly,
) {
  if (
    !hourly ||
    !Array.isArray(hourly.time)
  ) {
    return -1
  }

  // ---------------------------------
  // 1. Try activity time
  // ---------------------------------

  if (activityHour.value) {
    const activityIndex =
      hourly.time.indexOf(
        activityHour.value,
      )

    if (activityIndex !== -1) {
      return activityIndex
    }
  }

  // ---------------------------------
  // 2. Fall back to current time
  // ---------------------------------

  const currentIndex =
    hourly.time.indexOf(
      currentMelbourneHour.value,
    )

  if (currentIndex !== -1) {
    return currentIndex
  }

  return -1
}

// =========================
// Weather hour index
// =========================

const weatherHourIndex =
  computed(() => {
    const hourly =
      locationWeather.value
        ?.weather
        ?.hourly

    return findBestHourIndex(
      hourly,
    )
  })

// =========================
// Air quality hour index
// =========================

const airQualityHourIndex =
  computed(() => {
    const hourly =
      locationWeather.value
        ?.air_quality
        ?.hourly

    return findBestHourIndex(
      hourly,
    )
  })

// =========================
// Is activity forecast used?
// =========================
//
// Used only to determine whether
// the exact activity time was found.
//
const usingActivityForecast =
  computed(() => {
    if (
      !activityHour.value ||
      !locationWeather.value
    ) {
      return false
    }

    const weatherTimes =
      locationWeather.value
        ?.weather
        ?.hourly
        ?.time ?? []

    const airQualityTimes =
      locationWeather.value
        ?.air_quality
        ?.hourly
        ?.time ?? []

    return (
      weatherTimes.includes(
        activityHour.value,
      ) ||
      airQualityTimes.includes(
        activityHour.value,
      )
    )
  })

// =========================
// Read weather value
// =========================

function getWeatherValue(
  field,
) {
  const hourly =
    locationWeather.value
      ?.weather
      ?.hourly

  const index =
    weatherHourIndex.value

  if (
    !hourly ||
    index === -1
  ) {
    return null
  }

  return (
    hourly[field]?.[index] ??
    null
  )
}

// =========================
// Read air quality value
// =========================

function getAirQualityValue(
  field,
) {
  const hourly =
    locationWeather.value
      ?.air_quality
      ?.hourly

  const index =
    airQualityHourIndex.value

  if (
    !hourly ||
    index === -1
  ) {
    return null
  }

  return (
    hourly[field]?.[index] ??
    null
  )
}
</script>

<template>
  <div class="weather-card">
    <!-- =========================
         Loading
         ========================= -->
    <p
      v-if="loading"
      class="weather-message"
    >
      Loading weather...
    </p>

    <!-- =========================
         Error
         ========================= -->
    <p
      v-else-if="errorMessage"
      class="weather-message"
    >
      {{ errorMessage }}
    </p>

    <!-- =========================
         No matching suburb
         ========================= -->
    <p
      v-else-if="!locationWeather"
      class="weather-message"
    >
      Local weather unavailable
    </p>

    <!-- =========================
         No usable hourly data
         ========================= -->
    <p
      v-else-if="
        weatherHourIndex === -1 &&
        airQualityHourIndex === -1
      "
      class="weather-message"
    >
      Local conditions unavailable
    </p>

    <!-- =========================
         Weather available
         ========================= -->
    <div v-else>
      <div class="weather-header">
        <div>
          <strong>
            {{
              usingActivityForecast
                ? 'Activity conditions'
                : 'Local conditions'
            }}
          </strong>

          <small
            v-if="
              !usingActivityForecast &&
              activityTime
            "
            class="weather-fallback-note"
          >
            Current conditions
          </small>
        </div>

        <span>
          {{ suburb }}
        </span>
      </div>

      <div class="weather-values">
        <!-- =====================
             Temperature
             ===================== -->
        <div>
          <span class="weather-label">
            Temperature
          </span>

          <strong>
            <template
              v-if="
                getWeatherValue(
                  'temperature_2m',
                ) !== null
              "
            >
              {{
                getWeatherValue(
                  'temperature_2m',
                )
              }}°C
            </template>

            <template v-else>
              N/A
            </template>
          </strong>
        </div>

        <!-- =====================
             Rain
             ===================== -->
        <div>
          <span class="weather-label">
            Rain
          </span>

          <strong>
            <template
              v-if="
                getWeatherValue(
                  'precipitation_probability',
                ) !== null
              "
            >
              {{
                getWeatherValue(
                  'precipitation_probability',
                )
              }}%
            </template>

            <template v-else>
              N/A
            </template>
          </strong>
        </div>

        <!-- =====================
             UV
             ===================== -->
        <div>
          <span class="weather-label">
            UV
          </span>

          <strong>
            {{
              getWeatherValue(
                'uv_index',
              ) ?? 'N/A'
            }}
          </strong>
        </div>

        <!-- =====================
             Air quality
             ===================== -->
        <div>
          <span class="weather-label">
            AQI (US)
          </span>

          <strong>
            {{
              getAirQualityValue(
                'us_aqi',
              ) ?? 'N/A'
            }}
          </strong>
        </div>
      </div>

      <small class="weather-source">
        Source: Open-Meteo
      </small>
    </div>
  </div>
</template>

<style scoped>
.weather-card {
  margin-top: 16px;
  padding: 16px;
  border: 1px solid #d8dedb;
  border-radius: 10px;
  background: #f7faf8;
}

.weather-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 12px;
  margin-bottom: 14px;
}

.weather-header > div {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.weather-header span {
  color: #5f6b65;
}

.weather-fallback-note {
  color: #68736e;
  font-size: 12px;
  font-weight: 400;
}

.weather-values {
  display: grid;
  grid-template-columns:
    repeat(4, 1fr);
  gap: 12px;
}

.weather-values > div {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.weather-label {
  font-size: 14px;
  color: #5f6b65;
}

.weather-values strong {
  font-size: 18px;
}

.weather-source {
  display: block;
  margin-top: 12px;
  color: #68736e;
}

.weather-message {
  margin: 0;
  color: #5f6b65;
}

@media (max-width: 700px) {
  .weather-values {
    grid-template-columns:
      repeat(2, 1fr);
  }
}
</style>