<script setup>
// ======================================================
// Activity filter component
// ======================================================
//
// ActivityFilters is responsible only for collecting
// filter input from the user.
//
// It does NOT perform the actual filtering itself.
//
// Main data flow:
//
// ActivitiesView
//   ↓ passes current filters + available options
// ActivityFilters
//   ↓ user changes a field
// emit update:filters
//   ↓
// ActivitiesView
//   ↓
// filteredActivities recalculates
//
// The Clear button follows a similar pattern:
//
// ActivityFilters
//   ↓ emit clear
// ActivitiesView
//   ↓
// reset all filters to default values
//


// ======================================================
// Props received from ActivitiesView
// ======================================================

const props = defineProps({
  // Current filter selections.
  //
  // Example:
  //
  // {
  //   search: '',
  //   area: '',
  //   interest: '',
  //   day: '',
  //   recurrence: '',
  //   suitability: 'all'
  // }
  filters: {
    type: Object,
    required: true,
  },

  // Available suburbs generated dynamically
  // from the current activity catalogue.
  areas: {
    type: Array,
    default: () => [],
  },

  // Available activity interests derived
  // from activity tags.
  interests: {
    type: Array,
    default: () => [],
  },

  // Available activity days.
  days: {
    type: Array,
    default: () => [],
  },

  // Available recurrence / schedule types.
  recurrenceOptions: {
    type: Array,
    default: () => [],
  },
})


// ======================================================
// Events sent to ActivitiesView
// ======================================================
//
// update:filters
//   Sends a complete updated filter object back
//   to the parent page.
//
// clear
//   Requests the parent page to restore all filters
//   to their default values.
//
const emit = defineEmits([
  'update:filters',
  'clear',
])


// ======================================================
// Update one filter field
// ======================================================
//
// Props are read-only in Vue, so this component does
// not modify props.filters directly.
//
// Instead, it creates a new filter object by copying
// the existing values and replacing only the field
// that the user changed.
//
// Example:
//
// updateField('area', 'Clayton')
//
// {
//   ...currentFilters,
//   area: 'Clayton'
// }
//
// The updated object is then emitted to ActivitiesView.
//
const updateField = (field, value) => {
  emit('update:filters', {
    ...props.filters,
    [field]: value,
  })
}
</script>

<template>
  <!-- ==============================================
       Activity filter panel
  =============================================== -->
  <section
    class="activity-filter-panel"
    aria-labelledby="activity-filter-heading"
  >
    <!-- ============================================
         Filter panel heading
    ============================================= -->
    <div class="activity-filter-heading">
      <div>
        <p class="activity-filter-kicker">
          Refine your results
        </p>

        <h2 id="activity-filter-heading">
          Find activities that suit you
        </h2>
      </div>

      <!--
        The child component does not reset filters
        directly.

        It emits "clear" so ActivitiesView can restore
        the default filter state.
      -->
      <button
        class="clear-filter-button"
        type="button"
        @click="emit('clear')"
      >
        Clear filters
      </button>
    </div>


    <!-- ============================================
         Filter controls
    ============================================= -->
    <div class="activity-filter-grid">

      <!-- ==========================================
           Free-text search
      =========================================== -->
      <!--
        Search text is sent to ActivitiesView on every
        input event.

        The parent component decides which activity
        fields are included in the search.
      -->
      <div class="activity-filter-field filter-field--search">
        <label for="activity-search">
          Search
        </label>

        <input
          id="activity-search"
          type="search"
          :value="filters.search"
          placeholder="Try walking, technology, knitting..."
          @input="
            updateField(
              'search',
              $event.target.value,
            )
          "
        />
      </div>


      <!-- ==========================================
           General area filter
      =========================================== -->
      <!--
        Area options are generated by ActivitiesView
        from the suburbs available in the activity data.
      -->
      <div class="activity-filter-field">
        <label for="activity-area">
          General area
        </label>

        <select
          id="activity-area"
          :value="filters.area"
          @change="
            updateField(
              'area',
              $event.target.value,
            )
          "
        >
          <option value="">
            All areas
          </option>

          <option
            v-for="area in areas"
            :key="area"
            :value="area"
          >
            {{ area }}
          </option>
        </select>
      </div>


      <!-- ==========================================
           Interest filter
      =========================================== -->
      <!--
        Interest options are derived from activity tags
        and supplied by ActivitiesView.
      -->
      <div class="activity-filter-field">
        <label for="activity-interest">
          Interest
        </label>

        <select
          id="activity-interest"
          :value="filters.interest"
          @change="
            updateField(
              'interest',
              $event.target.value,
            )
          "
        >
          <option value="">
            All interests
          </option>

          <option
            v-for="interest in interests"
            :key="interest"
            :value="interest"
          >
            {{ interest }}
          </option>
        </select>
      </div>


      <!-- ==========================================
           Preferred day filter
      =========================================== -->
      <!--
        Only days that exist in the current activity
        catalogue are displayed.
      -->
      <div class="activity-filter-field">
        <label for="activity-day">
          Preferred day
        </label>

        <select
          id="activity-day"
          :value="filters.day"
          @change="
            updateField(
              'day',
              $event.target.value,
            )
          "
        >
          <option value="">
            Any day
          </option>

          <option
            v-for="day in days"
            :key="day"
            :value="day"
          >
            {{ day }}
          </option>
        </select>
      </div>


      <!-- ==========================================
           Schedule / recurrence filter
      =========================================== -->
      <!--
        Recurrence options are generated from the
        activity catalogue rather than hard-coded.
      -->
      <div class="activity-filter-field">
        <label for="activity-recurrence">
          Schedule type
        </label>

        <select
          id="activity-recurrence"
          :value="filters.recurrence"
          @change="
            updateField(
              'recurrence',
              $event.target.value,
            )
          "
        >
          <option value="">
            Any schedule
          </option>

          <option
            v-for="option in recurrenceOptions"
            :key="option"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>


      <!-- ==========================================
           Older-adult suitability filter
      =========================================== -->
      <!--
        This filter uses the normalised suitability
        values produced by activityService.

        all
          → no suitability restriction

        yes
          → explicitly marked suitable

        partial
          → may be suitable
      -->
      <div class="activity-filter-field">
        <label for="activity-suitability">
          Older-adult relevance
        </label>

        <select
          id="activity-suitability"
          :value="filters.suitability"
          @change="
            updateField(
              'suitability',
              $event.target.value,
            )
          "
        >
          <option value="all">
            All relevance levels
          </option>

          <option value="yes">
            Marked suitable
          </option>

          <option value="partial">
            May be suitable
          </option>
        </select>
      </div>
    </div>
  </section>
</template>